---

- include: "config_kvm_{{ ansible_os_family | lower }}.yml"

- name: config_kvm | Configure module
  template:
    src: etc/modprobe.d/module.conf.j2
    dest: /etc/modprobe.d/vhost-net.conf
  vars:
    kvm_module: 'vhost-net'
    kvm_module_options: "{{ kvm_vhost_net_options }}"
  when: kvm_vhost_net_options is defined

- name: config_kvm | configuring kvm
  template:
    src: etc/libvirt/libvirtd.conf.j2
    dest: /etc/libvirt/libvirtd.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: "restart {{ kvm_service_name }}"
  when: not ansible_check_mode

- name: config_kvm | Ensuring libvirtd Service Is Enabled and Started
  service:
    name: "{{ kvm_service_name }}"
    enabled: true
    state: started
  become: true
